In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
import requests
import json
from dotenv import load_dotenv
load_dotenv()

True

In [2]:
data=pd.read_csv('../movies/Movie_Data.csv' , encoding='1252')
data.head(10)

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0
5,6,The Great Wall,"Action,Adventure,Fantasy",European mercenaries searching for black powde...,Yimou Zhang,"Matt Damon, Tian Jing, Willem Dafoe, Andy Lau",2016,103,6.1,56036,45.13,42.0
6,7,La La Land,"Comedy,Drama,Music",A jazz pianist falls for an aspiring actress i...,Damien Chazelle,"Ryan Gosling, Emma Stone, Rosemarie DeWitt, J....",2016,128,8.3,258682,151.06,93.0
7,8,Mindhorn,Comedy,A has-been actor best known for playing the ti...,Sean Foley,"Essie Davis, Andrea Riseborough, Julian Barrat...",2016,89,6.4,2490,NaN,71.0
8,9,The Lost City of Z,"Action,Adventure,Biography","A true-life drama, centering on British explor...",James Gray,"Charlie Hunnam, Robert Pattinson, Sienna Mille...",2016,141,7.1,7188,8.01,78.0
9,10,Passengers,"Adventure,Drama,Romance",A spacecraft traveling to a distant colony pla...,Morten Tyldum,"Jennifer Lawrence, Chris Pratt, Michael Sheen,...",2016,116,7.0,192177,100.01,41.0

In [3]:
data.shape

(1000, 12)

In [4]:
data.info

<bound method DataFrame.info of      Rank                    Title                     Genre  \
0       1  Guardians of the Galaxy   Action,Adventure,Sci-Fi
1       2               Prometheus  Adventure,Mystery,Sci-Fi
2       3                    Split           Horror,Thriller
3       4                     Sing   Animation,Comedy,Family
4       5            Suicide Squad  Action,Adventure,Fantasy
..    ...                      ...                       ...
995   996     Secret in Their Eyes       Crime,Drama,Mystery
996   997          Hostel: Part II                    Horror
997   998   Step Up 2: The Streets       Drama,Music,Romance
998   999             Search Party          Adventure,Comedy
999  1000               Nine Lives     Comedy,Family,Fantasy

                                           Description              Director  \
0    A group of intergalactic criminals are forced ...            James Gunn
1    Following clues to the origin of mankind, a te...          Ridley Scott
2    Three girls are kidnapped by a man with a diag...    M. Night Shyamalan
3    In a city of humanoid animals, a hustling thea...  Christophe Lourdelet
4    A secret government agency recruits some of th...            David Ayer
..                                                 ...                   ...
995  A tight-knit team of rising investigators, alo...             Billy Ray
996  Three American college students studying abroa...              Eli Roth
997  Romantic sparks occur between two dance studen...            Jon M. Chu
998  A pair of friends embark on a mission to reuni...        Scot Armstrong
999  A stuffy businessman finds himself trapped ins...      Barry Sonnenfeld

                                                Actors  Year  \
0    Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...  2014
1    Noomi Rapace, Logan Marshall-Green, Michael Fa...  2012
2    James McAvoy, Anya Taylor-Joy, Haley Lu Richar...  2016
3    Matthew McConaughey,Reese Witherspoon, Seth Ma...  2016
4    Will Smith, Jared Leto, Margot Robbie, Viola D...  2016
..                                                 ...   ...
995  Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...  2015
996  Lauren German, Heather Matarazzo, Bijou Philli...  2007
997  Robert Hoffman, Briana Evigan, Cassie Ventura,...  2008
998  Adam Pally, T.J. Miller, Thomas Middleditch,Sh...  2014
999  Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...  2016

     Runtime (Minutes)  Rating   Votes  Revenue (Millions)  Metascore
0                  121     8.1  757074              333.13       76.0
1                  124     7.0  485820              126.46       65.0
2                  117     7.3  157606              138.12       62.0
3                  108     7.2   60545              270.32       59.0
4                  123     6.2  393727              325.02       40.0
..                 ...     ...     ...                 ...        ...
995                111     6.2   27585                 NaN       45.0
996                 94     5.5   73152               17.54       46.0
997                 98     6.2   70699               58.01       50.0
998                 93     5.6    4881                 NaN       22.0
999                 87     5.3   12435               19.64       11.0

[1000 rows x 12 columns]>

In [5]:
data.dtypes

Rank                    int64
Title                  object
Genre                  object
Description            object
Director               object
Actors                 object
Year                    int64
Runtime (Minutes)       int64
Rating                float64
Votes                   int64
Revenue (Millions)    float64
Metascore             float64
dtype: object

In [6]:
data.isnull().values.any()

True

In [7]:
data.isnull().sum().sum()

192

In [8]:
data.isnull().sum()

Rank                    0
Title                   0
Genre                   0
Description             0
Director                0
Actors                  0
Year                    0
Runtime (Minutes)       0
Rating                  0
Votes                   0
Revenue (Millions)    128
Metascore              64
dtype: int64

In [9]:
data.columns

Index(['Rank', 'Title', 'Genre', 'Description', 'Director', 'Actors', 'Year',
       'Runtime (Minutes)', 'Rating', 'Votes', 'Revenue (Millions)',
       'Metascore'],
      dtype='object')

In [10]:
data1=data[['Genre','Director','Title','Year','Rating','Revenue (Millions)']]
data1

,Genre,Director,Title,Year,Rating,Revenue (Millions)
0,"Action,Adventure,Sci-Fi",James Gunn,Guardians of the Galaxy,2014,8.1,333.13
1,"Adventure,Mystery,Sci-Fi",Ridley Scott,Prometheus,2012,7.0,126.46
2,"Horror,Thriller",M. Night Shyamalan,Split,2016,7.3,138.12
3,"Animation,Comedy,Family",Christophe Lourdelet,Sing,2016,7.2,270.32
4,"Action,Adventure,Fantasy",David Ayer,Suicide Squad,2016,6.2,325.02
...,...,...,...,...,...,...
995,"Crime,Drama,Mystery",Billy Ray,Secret in Their Eyes,2015,6.2,NaN
996,Horror,Eli Roth,Hostel: Part II,2007,5.5,17.54
997,"Drama,Music,Romance",Jon M. Chu,Step Up 2: The Streets,2008,6.2,58.01
998,"Adventure,Comedy",Scot Armstrong,Search Party,2014,5.6,NaN
999,"Comedy,Family,Fantasy",Barry Sonnenfeld,Nine Lives,2016,5.3,19.64

In [11]:
data1=data1.rename(columns = {'Revenue (Millions)':'Revenue(M$)'})
data1

,Genre,Director,Title,Year,Rating,Revenue(M$)
0,"Action,Adventure,Sci-Fi",James Gunn,Guardians of the Galaxy,2014,8.1,333.13
1,"Adventure,Mystery,Sci-Fi",Ridley Scott,Prometheus,2012,7.0,126.46
2,"Horror,Thriller",M. Night Shyamalan,Split,2016,7.3,138.12
3,"Animation,Comedy,Family",Christophe Lourdelet,Sing,2016,7.2,270.32
4,"Action,Adventure,Fantasy",David Ayer,Suicide Squad,2016,6.2,325.02
...,...,...,...,...,...,...
995,"Crime,Drama,Mystery",Billy Ray,Secret in Their Eyes,2015,6.2,NaN
996,Horror,Eli Roth,Hostel: Part II,2007,5.5,17.54
997,"Drama,Music,Romance",Jon M. Chu,Step Up 2: The Streets,2008,6.2,58.01
998,"Adventure,Comedy",Scot Armstrong,Search Party,2014,5.6,NaN
999,"Comedy,Family,Fantasy",Barry Sonnenfeld,Nine Lives,2016,5.3,19.64

In [12]:
data1['Revenue(M$)'].fillna(0, inplace=True)
data1

,Genre,Director,Title,Year,Rating,Revenue(M$)
0,"Action,Adventure,Sci-Fi",James Gunn,Guardians of the Galaxy,2014,8.1,333.13
1,"Adventure,Mystery,Sci-Fi",Ridley Scott,Prometheus,2012,7.0,126.46
2,"Horror,Thriller",M. Night Shyamalan,Split,2016,7.3,138.12
3,"Animation,Comedy,Family",Christophe Lourdelet,Sing,2016,7.2,270.32
4,"Action,Adventure,Fantasy",David Ayer,Suicide Squad,2016,6.2,325.02
...,...,...,...,...,...,...
995,"Crime,Drama,Mystery",Billy Ray,Secret in Their Eyes,2015,6.2,0.00
996,Horror,Eli Roth,Hostel: Part II,2007,5.5,17.54
997,"Drama,Music,Romance",Jon M. Chu,Step Up 2: The Streets,2008,6.2,58.01
998,"Adventure,Comedy",Scot Armstrong,Search Party,2014,5.6,0.00
999,"Comedy,Family,Fantasy",Barry Sonnenfeld,Nine Lives,2016,5.3,19.64

In [13]:
data1.sort_values(by=['Year'], ascending=False,inplace=True)
data1

,Genre,Director,Title,Year,Rating,Revenue(M$)
999,"Comedy,Family,Fantasy",Barry Sonnenfeld,Nine Lives,2016,5.3,19.64
161,"Action,Comedy,Crime",Ben Wheatley,Free Fire,2016,7.0,1.80
647,"Fantasy,Horror,Thriller",Jonathan Holbrook,Tall Men,2016,3.2,0.00
234,"Action,Adventure,Drama",Cedric Nicolas-Troyan,The Huntsman: Winter's War,2016,6.1,47.95
653,"Comedy,Music",Akiva Schaffer,Popstar: Never Stop Never Stopping,2016,6.7,9.39
...,...,...,...,...,...,...
715,"Animation,Comedy,Family",George Miller,Happy Feet,2006,6.5,197.99
727,"Drama,Mystery,Romance",Neil Burger,The Illusionist,2006,7.6,39.83
965,"Drama,Mystery,Thriller",David Lynch,Inland Empire,2006,7.0,0.00
559,"Adventure,Comedy,Sci-Fi",Mike Judge,Idiocracy,2006,6.6,0.44
230,"Drama,Fantasy,War",Guillermo del Toro,Pan's Labyrinth,2006,8.2,37.62

In [14]:
data2=data1.set_index('Year')
data2

,Genre,Director,Title,Rating,Revenue(M$)
Year,,,,,
2016,"Comedy,Family,Fantasy",Barry Sonnenfeld,Nine Lives,5.3,19.64
2016,"Action,Comedy,Crime",Ben Wheatley,Free Fire,7.0,1.80
2016,"Fantasy,Horror,Thriller",Jonathan Holbrook,Tall Men,3.2,0.00
2016,"Action,Adventure,Drama",Cedric Nicolas-Troyan,The Huntsman: Winter's War,6.1,47.95
2016,"Comedy,Music",Akiva Schaffer,Popstar: Never Stop Never Stopping,6.7,9.39
...,...,...,...,...,...
2006,"Animation,Comedy,Family",George Miller,Happy Feet,6.5,197.99
2006,"Drama,Mystery,Romance",Neil Burger,The Illusionist,7.6,39.83
2006,"Drama,Mystery,Thriller",David Lynch,Inland Empire,7.0,0.00
2006,"Adventure,Comedy,Sci-Fi",Mike Judge,Idiocracy,6.6,0.44
2006,"Drama,Fantasy,War",Guillermo del Toro,Pan's Labyrinth,8.2,37.62

In [15]:
data2.sort_values(by=['Rating'], ascending=False,inplace=True)
data2.head(10)

,Genre,Director,Title,Rating,Revenue(M$)
Year,,,,,
2008,"Action,Crime,Drama",Christopher Nolan,The Dark Knight,9.0,533.32
2016,"Action,Biography,Drama",Nitesh Tiwari,Dangal,8.8,11.15
2010,"Action,Adventure,Sci-Fi",Christopher Nolan,Inception,8.8,292.57
2014,"Adventure,Drama,Sci-Fi",Christopher Nolan,Interstellar,8.6,187.99
2011,"Biography,Comedy,Drama",Olivier Nakache,The Intouchables,8.6,13.18
2016,"Animation,Drama,Fantasy",Makoto Shinkai,Kimi no na wa,8.6,4.68
2014,"Drama,Music",Damien Chazelle,Whiplash,8.5,13.09
2006,"Drama,Thriller",Florian Henckel von Donnersmarck,The Lives of Others,8.5,11.28
2012,"Action,Thriller",Christopher Nolan,The Dark Knight Rises,8.5,448.13
2006,"Drama,Mystery,Sci-Fi",Christopher Nolan,The Prestige,8.5,53.08

In [16]:
url = "https://imdb8.p.rapidapi.com"
response = requests.get(url)
response

He probado con estas tres combinaciones diferentes y ninguna ha funcionado así que finalmente he optado por utilizar el token de forma visible ejecutar el código,borrarlo después y subirlo ya borrado a github.

def getFromRAPI(endpoint, queryParams={}):
    url = f"https://imdb8.p.rapidapi.com{endpoint}"
    querystring = {"tconst":"tt0944947"}
    apiKey = os.getenv("RAPIKEY")
    if not apiKey:
        raise ValueError("Please setup the RAPIKEY env variable")
    headers = {
        'x-rapidapi-host': "imdb8.p.rapidapi.com"
        'Authorization' : f"token {apiKey}"
    }
    
    res = requests.get(url, headers=headers, params=querystring)
    print(res.url)
    return res.json()

url = "https://imdb8.p.rapidapi.com/title/get-top-cast"

querystring = {"tconst":"tt0944947"}
apiKey = os.getenv("RAPIKEY")
headers = {
    'x-rapidapi-host': "imdb8.p.rapidapi.com",
    'x-rapidapi-key': f"token{apiKey}"
    }

response = requests.request("GET", url, headers=headers, params=querystring)

print(response.text)

import requests

url = "https://imdb8.p.rapidapi.com/title/get-top-cast"

querystring = {"tconst":"tt0944947"}

headers = {
    'x-rapidapi-host': "imdb8.p.rapidapi.com",
    'x-rapidapi-key': ""
    }

response = requests.request("GET", url, headers=headers, params=querystring)

print(response.text)

In [25]:
import requests

url = "https://imdb8.p.rapidapi.com/title/get-versions"

querystring = {"tconst":"tt0944947"}

headers = {
    'x-rapidapi-host': "imdb8.p.rapidapi.com",
    'x-rapidapi-key': ""
    }

response = requests.request("GET", url, headers=headers, params=querystring)

response.text
d=response.json()
d

{'@type': 'imdb.api.title.versions',
 'alternateTitles': [{'region': 'SI',
   'title': 'Igra prestolov',
   'types': ['imdbDisplay']},
  {'region': 'US', 'title': 'A Song of Ice and Fire', 'types': ['working']},
  {'region': 'LT', 'title': 'Sostų karai', 'types': ['imdbDisplay']},
  {'attributes': ['literal title'],
   'language': 'fa',
   'region': 'IR',
   'title': 'Baziye tajo takht'},
  {'region': 'RO', 'title': 'Urzeala tronurilor', 'types': ['imdbDisplay']},
  {'title': 'Game of Thrones', 'types': ['original']},
  {'language': 'hi',
   'region': 'IN',
   'title': 'Game of Thrones',
   'types': ['imdbDisplay']},
  {'attributes': ['DVD box title'],
   'region': 'FR',
   'title': 'Game of Thrones - Le trône de fer'},
  {'region': 'AU', 'title': 'Game of Thrones', 'types': ['imdbDisplay']},
  {'language': 'tr',
   'region': 'TR',
   'title': 'Taht Oyunları',
   'types': ['imdbDisplay']},
  {'region': 'LV', 'title': 'Troņu spēle', 'types': ['imdbDisplay']},
  {'region': 'GB', 'title': 'Game of Thrones', 'types': ['imdbDisplay']},
  {'region': 'HU', 'title': 'Trónok harca', 'types': ['imdbDisplay']},
  {'region': 'ES', 'title': 'Juego de tronos', 'types': ['imdbDisplay']},
  {'attributes': ['literal title'],
   'region': 'BR',
   'title': 'Jogo dos Tronos'},
  {'region': 'UA', 'title': 'Гра престолів', 'types': ['imdbDisplay']},
  {'language': 'bg',
   'region': 'BG',
   'title': 'Игра на тронове',
   'types': ['imdbDisplay']},
  {'region': 'RU', 'title': 'Игра престолов', 'types': ['imdbDisplay']},
  {'language': 'en',
   'region': 'CA',
   'title': 'Game of Thrones',
   'types': ['imdbDisplay']},
  {'region': 'DE',
   'title': 'Game of Thrones: Das Lied von Eis und Feuer',
   'types': ['imdbDisplay']},
  {'region': 'AR', 'title': 'Game of Thrones', 'types': ['imdbDisplay']},
  {'region': 'CZ', 'title': 'Hra o trůny', 'types': ['imdbDisplay']},
  {'attributes': ['literal English title'],
   'language': 'en',
   'region': 'JP',
   'title': 'Game of Thrones'},
  {'region': 'RS', 'title': 'Игра престола', 'types': ['imdbDisplay']},
  {'region': 'BR', 'title': 'A Guerra dos Tronos', 'types': ['alternative']},
  {'attributes': ['short title'],
   'language': 'en',
   'region': 'XWW',
   'title': 'GoT'},
  {'region': 'EE', 'title': 'Troonide mäng', 'types': ['imdbDisplay']},
  {'region': 'US', 'title': 'Game of Thrones', 'types': ['imdbDisplay']},
  {'region': 'DE', 'title': 'Game of Thrones', 'types': ['alternative']},
  {'region': 'IT', 'title': 'Il trono di spade', 'types': ['imdbDisplay']},
  {'region': 'TW', 'title': '冰與火之歌：權力遊戲', 'types': ['imdbDisplay']},
  {'attributes': ['dubbed version'],
   'region': 'AR',
   'title': 'El Juego de Tronos'},
  {'region': 'AL', 'title': 'Froni i shpatave', 'types': ['imdbDisplay']},
  {'region': 'GE',
   'title': 'Samefo Karis Tamashebi',
   'types': ['imdbDisplay']},
  {'language': 'ja',
   'region': 'JP',
   'title': 'ゲーム・オブ・スローンズ',
   'types': ['imdbDisplay']},
  {'region': 'VN', 'title': 'Trò Chơi Vương Quyền', 'types': ['imdbDisplay']},
  {'region': 'HR', 'title': 'Igra prijestolja', 'types': ['imdbDisplay']},
  {'region': 'CL', 'title': 'Game of Thrones', 'types': ['imdbDisplay']},
  {'attributes': ['alternative transliteration'],
   'region': 'GR',
   'title': 'Paihnidi tou stemmatos'},
  {'region': 'PT', 'title': 'A Guerra dos Tronos', 'types': ['imdbDisplay']},
  {'region': 'PL', 'title': 'Gra o tron', 'types': ['imdbDisplay']},
  {'region': 'MK', 'title': 'Игра на тронови', 'types': ['imdbDisplay']},
  {'region': 'MX', 'title': 'Game of Thrones', 'types': ['imdbDisplay']},
  {'region': 'GR',
   'title': 'Παιχνίδι του στέμματος',
   'types': ['imdbDisplay']},
  {'region': 'FR', 'title': 'Game of Thrones', 'types': ['imdbDisplay']},
  {'attributes': ['dubbed version'],
   'region': 'MX',
   'title': 'Juego de tronos'},
  {'language': 'en',
   'region': 'NZ',
   'title': 'Game of Thrones',
   'types': ['imdbDisplay']},
  {'attributes': ['informal short title'], 'region': 'US', 'title': 'GoT'},
  {'region': 'SK', 'title': 'Hra o tróny', 'types': ['imdbDisplay']}],
 'colorations': ['color'],
 'defaultTitle': 'Game of Thrones',
 'silent': False,
 'spokenLanguages': ['en'],
 'originalTitle': 'Game of Thrones',
 'origins': ['US', 'GB'],
 'runningTimes': [{'timeMinutes': 57}],
 'id': '/title/tt0944947/',
 'title': 'Game of Thrones',
 'titleType': 'tvSeries',
 'year': 2011}

In [26]:
import requests

url = "https://imdb8.p.rapidapi.com/title/get-parental-guide"

querystring = {"tconst":"tt0120338"}

headers = {
    'x-rapidapi-host': "imdb8.p.rapidapi.com",
    'x-rapidapi-key': ""
    }

response = requests.request("GET", url, headers=headers, params=querystring)

response.text
t=response.json()
t

{'parentalguide': [{'items': [{'hasProfanity': False,
     'id': '/title/tt0120338/parentalguide/pg0488374',
     'isSpoiler': False,
     'language': 'eng',
     'text': "Jack and Rose run inside a car. Rose kisses Jack's fingers. She puts his hand on her breast before having sex. They have sex (offscreen)."},
    {'hasProfanity': False,
     'id': '/title/tt0120338/parentalguide/pg0595712',
     'isSpoiler': False,
     'language': 'eng',
     'text': 'One female frontal naked body scene at about 20 seconds but there are no sexual activity.'},
    {'hasProfanity': False,
     'id': '/title/tt0120338/parentalguide/pg0664459',
     'isSpoiler': False,
     'language': 'eng',
     'text': 'Some kissing scenes between the main characters.'},
    {'hasProfanity': True,
     'id': '/title/tt0120338/parentalguide/pg0678472',
     'isSpoiler': False,
     'language': 'eng',
     'text': 'Rose lets Jack draw her fully nude. We see her bare breasts and butt.'},
    {'hasProfanity': False,
     'id': '/title/tt0120338/parentalguide/pg0084362',
     'isSpoiler': False,
     'language': 'eng',
     'text': 'There are several drawings of nude women. Full frontal nudity is shown (to note, they ARE drawings).'}],
   'label': 'nudity',
   'severityVotes': {'mildVotes': 81,
    'moderateVotes': 263,
    'noneVotes': 16,
    'severeVotes': 119,
    'status': 'moderate'}},
  {'items': [{'hasProfanity': False,
     'id': '/title/tt0120338/parentalguide/pg0469339',
     'isSpoiler': False,
     'language': 'eng',
     'text': 'A man punches another man in the stomach.'},
    {'hasProfanity': False,
     'id': '/title/tt0120338/parentalguide/pg0487991',
     'isSpoiler': False,
     'language': 'eng',
     'text': 'A woman punches a man in steerage. We see his bloodied nose.'},
    {'hasProfanity': False,
     'id': '/title/tt0120338/parentalguide/pg0488375',
     'isSpoiler': True,
     'language': 'eng',
     'text': 'A man falls off the tilting Titanic and hits the propeller, spinning many times before hitting the ocean. Many people get crushed by the Titanic or pieces of the Titanic.'},
    {'hasProfanity': False,
     'id': '/title/tt0120338/parentalguide/pg0488376',
     'isSpoiler': False,
     'language': 'eng',
     'text': 'A man on a small boat threatens to throw a woman off the boat unless she keeps her mouth shut.'},
    {'hasProfanity': False,
     'id': '/title/tt0120338/parentalguide/pg0488377',
     'isSpoiler': False,
     'language': 'eng',
     'text': 'A man and girl attempt to save a young boy left behind in the lower levels of the Titanic. The father comes and grabs the boy, pushing the man and running in the opposite direction. The man and the boy get killed by water. The other man and girl are swept by the water and crash hard against a cage.'},
    {'hasProfanity': False,
     'id': '/title/tt0120338/parentalguide/pg0488378',
     'isSpoiler': False,
     'language': 'eng',
     'text': 'A survivor grabs a woman with a life jacket and pushes her down, making him float. Another man comes by and punches him, saving the girl.'},
    {'hasProfanity': False,
     'id': '/title/tt0120338/parentalguide/pg0488379',
     'isSpoiler': False,
     'language': 'eng',
     'text': 'Characters slowly freeze to death in the ocean.'},
    {'hasProfanity': False,
     'id': '/title/tt0120338/parentalguide/pg0731469',
     'isSpoiler': True,
     'language': 'eng',
     'text': 'A man tries to survive and jumps off the boat but on screen he hits the gigantic propeller'},
    {'hasProfanity': False,
     'id': '/title/tt0120338/parentalguide/pg0084373',
     'isSpoiler': True,
     'language': 'eng',
     'text': 'The film tells the true story of the Titanic sinking. Lots of peril and disaster violence. People drown and freeze to death. People fall off of decks, dishes and furniture go all over the place. A man is briefly shown with blood on his face.'},
    {'hasProfanity': False,
     'id': '/title/tt0120338/parentalguide/pg0084374',
     'isSpoiler': False,
     'language': 'eng',
     'text': 'A man shoots at another man various times, but he does not get hit.'},
    {'hasProfanity': False,
     'id': '/title/tt0120338/parentalguide/pg0084375',
     'isSpoiler': True,
     'language': 'eng',
     'text': "An officer accidentally shoots a person dead. We see blood on his life jacket and on the deck floor. The officer then commits suicide by shooting himself on the head (no blood, but it's an intense scene)."}],
   'label': 'violence',
   'severityVotes': {'mildVotes': 60,
    'moderateVotes': 158,
    'noneVotes': 7,
    'severeVotes': 24,
    'status': 'moderate'}},
  {'items': [{'hasProfanity': False,
     'id': '/title/tt0120338/parentalguide/pg0657050',
     'isSpoiler': False,
     'language': 'eng',
     'text': "18 uses of 'damn' (9 paired with 'God')"},
    {'hasProfanity': True,
     'id': '/title/tt0120338/parentalguide/pg0671139',
     'isSpoiler': False,
     'language': 'eng',
     'text': "British profanity is also present, such as 6 uses of 'bloody' (including 'bleeding Christ'), 1 use of 'bugger', and 1 use of 'bollocks'"},
    {'hasProfanity': False,
     'id': '/title/tt0120338/parentalguide/pg0671142',
     'isSpoiler': False,
     'language': 'eng',
     'text': "19 uses of 'God', 3 uses of 'Jesus', 1 use of 'Christ', and 1 use of 'Jesus Christ' as exclamations"},
    {'hasProfanity': True,
     'id': '/title/tt0120338/parentalguide/pg0671143',
     'isSpoiler': False,
     'language': 'eng',
     'text': "3 uses of 'ass', including 1 use as 'arse' by an Irish man"},
    {'hasProfanity': True,
     'id': '/title/tt0120338/parentalguide/pg0671144',
     'isSpoiler': False,
     'language': 'eng',
     'text': "6 uses of 'bastard', including 2 uses of the Italian word 'bastardo'"},
    {'hasProfanity': False,
     'id': '/title/tt0120338/parentalguide/pg0671145',
     'isSpoiler': False,
     'language': 'eng',
     'text': "6 uses of 'hell' (1 paired with 'bloody')"},
    {'hasProfanity': True,
     'id': '/title/tt0120338/parentalguide/pg0671147',
     'isSpoiler': False,
     'language': 'eng',
     'text': "2 uses of the Italian word 'puttana' (whore), including 1 use of 'figlio di puttana' (son of a bitch)"},
    {'hasProfanity': True,
     'id': '/title/tt0120338/parentalguide/pg0671148',
     'isSpoiler': False,
     'language': 'eng',
     'text': "2 uses of 'whore' and 1 use of 'slut' as insults"},
    {'hasProfanity': True,
     'id': '/title/tt0120338/parentalguide/pg0671149',
     'isSpoiler': False,
     'language': 'eng',
     'text': "1 use of the Italian profane term 'fanculo' (f**k off)"},
    {'hasProfanity': False,
     'id': '/title/tt0120338/parentalguide/pg0084366',
     'isSpoiler': False,
     'language': 'eng',
     'text': 'A woman gives the middle finger to a man. Although the purpose of this seems to be comedic in nature.'},
    {'hasProfanity': True,
     'id': '/title/tt0120338/parentalguide/pg0084367',
     'isSpoiler': False,
     'language': 'eng',
     'text': "14 uses of 'shit' (1 paired with 'bull' and another with 'horse'), including 1 use as 'shite'"},
    {'hasProfanity': True,
     'id': '/title/tt0120338/parentalguide/pg0084370',
     'isSpoiler': False,
     'language': 'eng',
     'text': "3 uses of 'bitch' (all paired with 'son of a-', including one used in plural form)"},
    {'hasProfanity': False,
     'id': '/title/tt0120338/parentalguide/pg0084371',
     'isSpoiler': False,
     'language': 'eng',
     'text': "1 use of 'f**k' in a non-sexual manner (used for comedic effect)"}],
   'label': 'profanity',
   'severityVotes': {'mildVotes': 88,
    'moderateVotes': 144,
    'noneVotes': 9,
    'severeVotes': 22,
    'status': 'moderate'}},
  {'items': [{'hasProfanity': False,
     'id': '/title/tt0120338/parentalguide/pg0731470',
     'isSpoiler': False,
     'language': 'eng',
     'text': 'In the third-class party people are seen drinking.'},
    {'hasProfanity': False,
     'id': '/title/tt0120338/parentalguide/pg0084357',
     'isSpoiler': False,
     'language': 'eng',
     'text': 'People are shown drinking and smoking throughout the film.'}],
   'label': 'alcohol',
   'severityVotes': {'mildVotes': 186,
    'moderateVotes': 31,
    'noneVotes': 22,
    'severeVotes': 6,
    'status': 'mild'}},
  {'items': [{'hasProfanity': False,
     'id': '/title/tt0120338/parentalguide/pg0481438',
     'isSpoiler': False,
     'language': 'eng',
     'text': 'The sinking sequence is very distressing and intense. We get to see prolonged scenes of screaming, yelling and frantic passengers who are in peril, including women and children. These scenes are very distressing and may be frightening to others. The aftermath scene of the sinking may be disturbing and horrifying to some viewers, which showcases frozen bodies with pale greenish faces covered in frost, including bodies of a mother and her baby.'},
    {'hasProfanity': False,
     'id': '/title/tt0120338/parentalguide/pg0487767',
     'isSpoiler': True,
     'language': 'eng',
     'text': "One of the main characters is arrested and is placed in the lower decks of the ship, as it is sinking. Water is shown rising as he is handcuffed to a pole. His rescuer frantically searches for him in the lower parts of the ship, where gushing water is present. The ship's lights flicker on and off. Eerie rumbling sounds are heard during the sequence as she is the only person in that part of the ship. This whole sequence can be ominous and distressing to some viewers."},
    {'hasProfanity': False,
     'id': '/title/tt0120338/parentalguide/pg0487768',
     'isSpoiler': False,
     'language': 'eng',
     'text': 'Two main characters are trapped in the E deck behind locked gates as they try to escape the inundated level. Water is shown to rise higher and higher as the level is almost submerged. The characters would be in heavy peril during this long sequence, where they are in danger of drowning. Those suffering from claustrophobia would find this scene difficult to watch.'},
    {'hasProfanity': False,
     'id': '/title/tt0120338/parentalguide/pg0487769',
     'isSpoiler': False,
     'language': 'eng',
     'text': 'People (including women and children) are cruelly kept from entering the gates in the third class deck, as the ship starts to sink. They become rowdy and disorderly as the officers keep them where they push and shove each other, after only women and children only are ordered to enter.'},
    {'hasProfanity': False,
     'id': '/title/tt0120338/parentalguide/pg0487989',
     'isSpoiler': False,
     'language': 'eng',
     'text': 'A main character tries to commit suicide by jumping off from the ship at nighttime. She is warned that the water would be really cold and that alone would kill her. She accidentally falls off whilst climbing on the railing and screams desperately for help.'},
    {'hasProfanity': False,
     'id': '/title/tt0120338/parentalguide/pg0487990',
     'isSpoiler': False,
     'language': 'eng',
     'text': 'After seeing his fiance passionately embracing another man in the grand staircase, a character snatches a gun in madness, and chases the lovers down into the sinking ship, shooting at them multiple times. This scene is more suspenseful and exciting than downright distressing.'},
    {'hasProfanity': False,
     'id': '/title/tt0120338/parentalguide/pg0487993',
     'isSpoiler': True,
     'language': 'eng',
     'text': 'Jack dies from hypothermia in the cold Atlantic Ocean, and is survived by Rose. She repeatedly tells him that "there\'s a boat" in a desperate voice, but he is unresponsive. Acknowledging his death, she mourns over him and lets him submerge into the water. This scene is very intense and emotional and may cause viewers to cry.'},
    {'hasProfanity': False,
     'id': '/title/tt0120338/parentalguide/pg0487994',
     'isSpoiler': True,
     'language': 'eng',
     'text': 'We hear "is anybody alive out there" from the boatmen in a distorted and rather spooky manner, which would frighten some people, as a main character is lying lethargically on the door with a very pale, icy face, in the middle of the ocean besides her dead lover. To survive the night as she promised her dead lover, she tries to yell "come back" to the boats, but can\'t produce higher vocals as she lost her voice due the cold. This is distressing and nerve-racking as viewers would think the boat is leaving here all alone in the cold, dark ocean.'},
    {'hasProfanity': False,
     'id': '/title/tt0120338/parentalguide/pg0488031',
     'isSpoiler': True,
     'language': 'eng',
     'text': 'Besides the main female character, virtually everyone in the ocean seem to have died from exposure, where there is a ghastly silence. The music during this scene is very eerie and spooky. The dead bodies are all palish green in colour with ice crystals on them. One particular dead woman looks rather disturbing with her bulgy, dead, grey eyes, who is checked by the boatmen.'},
    {'hasProfanity': False,
     'id': '/title/tt0120338/parentalguide/pg0488035',
     'isSpoiler': True,
     'language': 'eng',
     'text': 'The surviving main character, who is lying on the door in the water, desperately tries to yell "come back", with her hoarse voice, to the boat that is presumably leaving and getting further away from her whereabouts. This scene may be very distressing and upsetting to viewers.'},
    {'hasProfanity': False,
     'id': '/title/tt0120338/parentalguide/pg0488306',
     'isSpoiler': False,
     'language': 'eng',
     'text': 'The main female character refuses to get on a boat after her mother, who is on the boat, pleads her to get on it. She dismisses her mother\'s maternal request by saying "goodbye mother" and walking off. Her mother gets frantic, yelling her name a couple of times as the boat is lowered. This scene may be emotional to those who have a strong relationship with their mother.'},
    {'hasProfanity': False,
     'id': '/title/tt0120338/parentalguide/pg0488308',
     'isSpoiler': False,
     'language': 'eng',
     'text': 'We see an old couple in bed, holding each other, whilst Nearer My God To Thee is playing. Water is shown emerging in their room. Right in the next scene, where the somber music is still playing, we see a mother reading her children a story inside a third class cabin. To note, these two scenes occur during the sinking. We are reminded that these two families will obviously not make it.'},
    {'hasProfanity': False,
     'id': '/title/tt0120338/parentalguide/pg0488320',
     'isSpoiler': False,
     'language': 'eng',
     'text': "Just as the ship plunges into the ocean, the two main characters are separated due to suction created by the ship under the water. The female main character comes out of the water and frantically looks for her lover but cannot seem to find him for a few moments. As the camera rises, we see hundreds of screaming and panicking people in the bitterly cold water calling for help. Two men try to 'drown' the main female character, using her as a buoy, just so that they can stay afloat."},
    {'hasProfanity': False,
     'id': '/title/tt0120338/parentalguide/pg0488380',
     'isSpoiler': False,
     'language': 'eng',
     'text': 'The beginning of the movie has real footage of the Titanic in its watery grave. You see items that belonged to the passengers. It is quiet eerie and a little spooky.'},
    {'hasProfanity': False,
     'id': '/title/tt0120338/parentalguide/pg0654676',
     'isSpoiler': False,
     'language': 'eng',
     'text': 'The movie starts out rather cheery and jovial in nature, but then turns into having a very dark and depressing tone.'},
    {'hasProfanity': False,
     'id': '/title/tt0120338/parentalguide/pg0671127',
     'isSpoiler': True,
     'language': 'eng',
     'text': 'The captain of Titanic locks himself in the wheelhouse, and as the ship sinks underwater the windows shatter and flood the room, drowning the captain.'},
    {'hasProfanity': False,
     'id': '/title/tt0120338/parentalguide/pg0084359',
     'isSpoiler': False,
     'language': 'eng',
     'text': "The second half may be emotional for some viewers, where characters are seen getting parted from their families as they're put in boats, including the main characters."}],
   'label': 'frightening',
   'severityVotes': {'mildVotes': 21,
    'moderateVotes': 90,
    'noneVotes': 9,
    'severeVotes': 182,
    'status': 'severe'}}]}

TypeError: can only concatenate list (not "dict") to list

In [27]:
import requests

url = "https://imdb8.p.rapidapi.com/title/get-awards-summary"

querystring = {"tconst":"tt0944947"}

headers = {
    'x-rapidapi-host': "imdb8.p.rapidapi.com",
    'x-rapidapi-key': ""
    }

response = requests.request("GET", url, headers=headers, params=querystring)

response.text
a=response.json()
a

{'@type': 'imdb.api.title.awardssummary',
 'awardsSummary': {'highlighted': {'awardName': 'Golden Globe',
   'count': 1,
   'eventId': '/event/ev0000292/',
   'isWinner': True},
  'otherNominationsCount': 604,
  'otherWinsCount': 374},
 'highlightedRanking': {'id': '/chart/ratings/toptv',
  'label': 'Top 250 TV',
  'rank': 10,
  'rankType': 'topTv'},
 'id': '/title/tt0944947/',
 'title': 'Game of Thrones',
 'titleType': 'tvSeries',
 'year': 2011}

In [28]:
import requests

url = "https://imdb8.p.rapidapi.com/title/get-filming-locations"

querystring = {"tconst":"tt0944947"}

headers = {
    'x-rapidapi-host': "imdb8.p.rapidapi.com",
    'x-rapidapi-key': ""
    }

response = requests.request("GET", url, headers=headers, params=querystring)

response.text
s=response.json()
s

{'@type': 'imdb.api.title.filminglocations',
 'base': {'id': '/title/tt0944947/',
  'image': {'height': 1500,
   'id': '/title/tt0944947/images/rm4204167425',
   'url': 'https://m.media-amazon.com/images/M/MV5BYTRiNDQwYzAtMzVlZS00NTI5LWJjYjUtMzkwNTUzMWMxZTllXkEyXkFqcGdeQXVyNDIzMzcwNjc@._V1_.jpg',
   'width': 1102},
  'runningTimeInMinutes': 57,
  'nextEpisode': '/title/tt1480055/',
  'numberOfEpisodes': 73,
  'seriesEndYear': 2019,
  'seriesStartYear': 2011,
  'title': 'Game of Thrones',
  'titleType': 'tvSeries',
  'year': 2011},
 'id': '/title/tt0944947/',
 'locations': [{'id': '/title/tt0944947/filminglocations/lc0820830',
   'interestingVotes': {'down': 10, 'up': 356},
   'location': 'Split, Split-Dalmatia County, Croatia'},
  {'id': '/title/tt0944947/filminglocations/lc0820831',
   'interestingVotes': {'down': 8, 'up': 210},
   'location': 'Vrsno, Sibenik, Croatia'},
  {'id': '/title/tt0944947/filminglocations/lc0449596',
   'interestingVotes': {'down': 21, 'up': 421},
   'location': 'Dubrovnik, Croatia'},
  {'id': '/title/tt0944947/filminglocations/lc0449602',
   'interestingVotes': {'down': 8, 'up': 190},
   'location': 'Ouarzazate, Morocco'},
  {'id': '/title/tt0944947/filminglocations/lc0449600',
   'interestingVotes': {'down': 11, 'up': 233},
   'location': 'Marrakech, Morocco'},
  {'attributes': ['studio'],
   'extras': ['CLA Studios, Ouarzazate, Morocco'],
   'id': '/title/tt0944947/filminglocations/lc0449590',
   'interestingVotes': {'down': 3, 'up': 97},
   'location': 'Atlas Corporation Studios, Ouarzazate, Morocco'},
  {'id': '/title/tt0944947/filminglocations/lc0449598',
   'interestingVotes': {'down': 3, 'up': 95},
   'location': 'Harland and Wolff Paint Hall, Titanic-Quarter, Belfast, County Antrim, Northern Ireland, UK'},
  {'id': '/title/tt0944947/filminglocations/lc0622867',
   'interestingVotes': {'down': 10, 'up': 197},
   'location': 'Iceland'},
  {'id': '/title/tt0944947/filminglocations/lc0449605',
   'interestingVotes': {'down': 5, 'up': 123},
   'location': 'Valletta, Malta'},
  {'id': '/title/tt0944947/filminglocations/lc0449601',
   'interestingVotes': {'down': 5, 'up': 117},
   'location': 'Mdina, Malta'},
  {'id': '/title/tt0944947/filminglocations/lc0927887',
   'interestingVotes': {'down': 4, 'up': 102},
   'location': 'Klis Fortress, Klis, Croatia'},
  {'id': '/title/tt0944947/filminglocations/lc0449599',
   'interestingVotes': {'down': 6, 'up': 126},
   'location': 'Magheramorne Quarry, Larne, County Antrim, Northern Ireland, UK'},
  {'id': '/title/tt0944947/filminglocations/lc0889669',
   'interestingVotes': {'down': 4, 'up': 99},
   'location': 'Seville, Andalucia, Spain'},
  {'extras': ['Winterfell'],
   'id': '/title/tt0944947/filminglocations/lc0449594',
   'interestingVotes': {'down': 5, 'up': 112},
   'location': 'Castle Ward, Strangford, County Down, Northern Ireland, UK'},
  {'extras': ['Water Gardens of Dorne'],
   'id': '/title/tt0944947/filminglocations/lc0985383',
   'interestingVotes': {'down': 1, 'up': 49},
   'location': 'Real Alcázar, Seville, Andalucia, Spain'},
  {'id': '/title/tt0944947/filminglocations/lc0449597',
   'interestingVotes': {'down': 5, 'up': 86},
   'location': 'Dwejra, Gozo Island, Malta'},
  {'id': '/title/tt0944947/filminglocations/lc0449595',
   'interestingVotes': {'down': 10, 'up': 132},
   'location': 'Doune Castle, Doune, Stirling, Scotland, UK'},
  {'id': '/title/tt0944947/filminglocations/lc0449603',
   'interestingVotes': {'down': 6, 'up': 92},
   'location': "Shane's Castle, County Antrim, Northern Ireland, UK"},
  {'id': '/title/tt0944947/filminglocations/lc0449591',
   'interestingVotes': {'down': 5, 'up': 79},
   'location': 'Ballymoney, County Antrim, Northern Ireland, UK'},
  {'id': '/title/tt0944947/filminglocations/lc0449604',
   'interestingVotes': {'down': 6, 'up': 88},
   'location': 'Tollymore Forest Park, Bryansford, County Down, Northern Ireland, UK'},
  {'id': '/title/tt0944947/filminglocations/lc0449592',
   'interestingVotes': {'down': 6, 'up': 87},
   'location': 'Belfast, County Antrim, Northern Ireland, UK'},
  {'id': '/title/tt0944947/filminglocations/lc0449593',
   'interestingVotes': {'down': 5, 'up': 72},
   'location': 'Carncastle, County Antrim, Northern Ireland, UK'},
  {'id': '/title/tt0944947/filminglocations/lc0927885',
   'interestingVotes': {'down': 1, 'up': 34},
   'location': 'Volcano, Skaftafell National Park, Iceland'},
  {'extras': ['City of Braavos'],
   'id': '/title/tt0944947/filminglocations/lc1232932',
   'interestingVotes': {'down': 1, 'up': 34},
   'location': 'Gerona, Catalonia, Spain'},
  {'extras': ['ramparts of Astapor'],
   'id': '/title/tt0944947/filminglocations/lc0927888',
   'interestingVotes': {'down': 3, 'up': 52},
   'location': 'Ramparts, Essaouira, Morocco'},
  {'extras': ['Tower of Joy'],
   'id': '/title/tt0944947/filminglocations/lc1232931',
   'interestingVotes': {'up': 21},
   'location': 'Castle of Zafra, Guadalajara, Castilla-La Mancha, Spain'},
  {'extras': ['Vaes Dothrak'],
   'id': '/title/tt0944947/filminglocations/lc1240268',
   'interestingVotes': {'up': 21},
   'location': 'El Chorrillo, Pechina, Almeria, Andalucia, Spain'},
  {'attributes': ['exterior'],
   'extras': ['Outskirts of Vaes Dothrak exterior scenes'],
   'id': '/title/tt0944947/filminglocations/lc1240267',
   'interestingVotes': {'up': 19},
   'location': 'Sierra de la Alhamilla, Almeria, Andalucia, Spain'},
  {'id': '/title/tt0944947/filminglocations/lc0927884',
   'interestingVotes': {'down': 3, 'up': 45},
   'location': 'Svínafellsjökull Glacier, Iceland'},
  {'extras': ['Peak of Meereen'],
   'id': '/title/tt0944947/filminglocations/lc1240269',
   'interestingVotes': {'up': 18},
   'location': 'Tower of Mesa Roldan, Carboneras, Almeria, Spain'},
  {'extras': ['Long Bridge of Volantis'],
   'id': '/title/tt0944947/filminglocations/lc1002349',
   'interestingVotes': {'down': 2, 'up': 33},
   'location': 'Cordoba, Andalucía, Spain'},
  {'attributes': ['exterior'],
   'extras': ['Dragonstone exterior scenes'],
   'id': '/title/tt0944947/filminglocations/lc1425030',
   'interestingVotes': {'up': 16},
   'location': 'San Juan de Gaztelugatxe, Bermeo, Vizcaya, País Vasco, Spain'},
  {'id': '/title/tt0944947/filminglocations/lc0927886',
   'interestingVotes': {'down': 3, 'up': 35},
   'location': "Giant's Causeway, County Antrim, Northern Ireland, UK"},
  {'extras': ['Fighting pit of Meereen'],
   'id': '/title/tt0944947/filminglocations/lc0985384',
   'interestingVotes': {'down': 3, 'up': 34},
   'location': 'Osuna, Sevilla, Andalucía, Spain'},
  {'extras': ['location'],
   'id': '/title/tt0944947/filminglocations/lc1000718',
   'interestingVotes': {'down': 2, 'up': 28},
   'location': 'Canet de Mar, Barcelona, Catalonia, Spain'},
  {'extras': ['Casterly Rock'],
   'id': '/title/tt0944947/filminglocations/lc1425033',
   'interestingVotes': {'up': 14},
   'location': 'Trujillo, Cáceres, Extremadura, Spain'},
  {'id': '/title/tt0944947/filminglocations/lc1425034',
   'interestingVotes': {'up': 13},
   'location': 'Cáceres, Cáceres, Extremadura, Spain'},
  {'id': '/title/tt0944947/filminglocations/lc1425035',
   'interestingVotes': {'up': 13},
   'location': 'Malpartida de Cáceres, Cáceres, Extremadura, Spain'},
  {'id': '/title/tt0944947/filminglocations/lc0845726',
   'interestingVotes': {'down': 18, 'up': 97},
   'location': 'Los Angeles, California, USA'},
  {'attributes': ['exterior'],
   'extras': ['Dragonstone beach exterior scenes'],
   'id': '/title/tt0944947/filminglocations/lc1425031',
   'interestingVotes': {'up': 12},
   'location': 'Barrika, Vizcaya, País Vasco, Spain'},
  {'attributes': ['exterior'],
   'extras': ['Dragonstone beach exterior scenes'],
   'id': '/title/tt0944947/filminglocations/lc1425032',
   'interestingVotes': {'up': 12},
   'location': 'Zumaia, Guipúzcoa, País Vasco, Spain'},
  {'extras': ['Frozen lake beyond the wall scenes'],
   'id': '/title/tt0944947/filminglocations/lc1440798',
   'interestingVotes': {'up': 11},
   'location': 'Wolf Hill Quarry, Belfast, County Antrim, Northern Ireland, UK'},
  {'extras': ['Dragonpit summit'],
   'id': '/title/tt0944947/filminglocations/lc1440801',
   'interestingVotes': {'up': 11},
   'location': 'Itálica, Santiponce, Sevilla, Andalucía, Spain'},
  {'id': '/title/tt0944947/filminglocations/lc1455576',
   'interestingVotes': {'up': 10},
   'location': 'Kastilac Fort, Kastel Gomilica, Kastela, Croatia'},
  {'extras': ['Interior castle'],
   'id': '/title/tt0944947/filminglocations/lc1440800',
   'interestingVotes': {'down': 1, 'up': 12},
   'location': 'Almodóvar del Río, Córdoba, Andalucía, Spain'},
  {'extras': ["Underground storage with skeletons of dragons in King's Landing"],
   'id': '/title/tt0944947/filminglocations/lc1440799',
   'interestingVotes': {'down': 1, 'up': 11},
   'location': 'Reales Atarazanas de Sevilla, Sevilla, Sevilla, Andalucía, Spain'},
  {'extras': ['House Martell, Water gardens of Dorne'],
   'id': '/title/tt0944947/filminglocations/lc1863779',
   'interestingVotes': {'up': 2},
   'location': 'La Alcazaba, Almería, Almería, Andalucia, Spain'}]}

AttributeError: 'list' object has no attribute 'update'